/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileChangeHandler */

#ifndef _Included_org_beynet_utils_nativ_FileChangeHandler
#define _Included_org_beynet_utils_nativ_FileChangeHandler
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Fd
 * Method:    natClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_beynet_utils_io_Fd_natClose
  (JNIEnv *, jobject,jint);

/*
 * Class:     Fd
 * Method:    natFsync
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_beynet_utils_io_Fd_natFsync
  (JNIEnv *, jobject,jint);


/*
 * Class:     FileChangeHandler
 * Method:    natInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_beynet_utils_event_file_FileChangeHandler_natInit
  (JNIEnv *, jobject);


/*
 * Class:     FileChangeHandler
 * Method:    natAddDirectory
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_org_beynet_utils_event_file_FileChangeHandler_natAddDirectory
  (JNIEnv *, jobject, jint, jstring);
  
/*
 * Class:     FileChangeHandler
 * Method:    natRemoveDirectory
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_org_beynet_utils_event_file_FileChangeHandler_natRemoveDirectory
  (JNIEnv *, jobject, jint, jint);


JNIEXPORT void JNICALL Java_org_beynet_utils_event_file_FileChangeHandler_natSelect 
(JNIEnv * env, jobject obj, jint fd,jint maxSeq);


#ifdef __cplusplus
}
#endif
#endif
